services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-cvvpgbk9c44c73f6kpu0-a.frankfurt-postgres.render.com:5432/bookshopdb
      - SPRING_DATASOURCE_USERNAME=bookshopuser
      - SPRING_DATASOURCE_PASSWORD=r17brMkSa0rvCVlSQPltXwuKCbzSGInH


volumes:
  postgres_data:
