services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:jdbc:postgresql://dpg-cvvpgbk9c44c73f6kpu0-a.frankfurt-postgres.render.com:5432/bookshopdb
      - SPRING_DATASOURCE_USERNAME=bookshopuser
      - SPRING_DATASOURCE_PASSWORD=r17brMkSa0rvCVlSQPltXwuKCbzSGInH
    depends_on:
      - db

#  db:
#    image: postgres:16
#    environment:
#      - POSTGRES_DB=myapp
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
